### PR TITLE
Implement workaround for axios not passing Content-Length headers in multipart fields

### PR DESCRIPTION
**Pull request by MHHukiewitz**
To keep the old way of uploading files working. Reimplementation of #535

### CODE REVIEW

**Comment by MHHukiewitz** [comment]
This is what is currently deployed on api3.aleph.im

**Comment by hoh** [comment]
This code is quite convoluted and can be simplified. Here is my proposal: https://github.com/aleph-im/pyaleph/pull/545

**Comment by MHHukiewitz** [comment]
Closed in favor of #545

**Review by nesitor — APPROVED** [review]
LGTM

**Pull request merged**
